# Generated by Django 5.0.7 on 2024-08-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_comment_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="post_images/"),
        ),
        migrations.AddField(
            model_name="post",
            name="short_description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
